# Use an official Python runtime as a base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /workdir

# Copy the current directory contents into the container
COPY . /workdir

# Install the required Python packages
RUN pip install --no-cache-dir flask

# Run the application
CMD ["python", "/workdir/scripts/traffic_server.py"]
