version: "2"

run:
  timeout: 5m
  concurrency: 4

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
    - bodyclose
    - dupl
    - durationcheck
    - errcheck
    - copyloopvar
    - cyclop
    - goconst
    - gocritic
    - gocognit
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - rowserrcheck
    - spancheck
    - staticcheck
    - sqlclosecheck
    - unconvert
    - usestdlibvars
    - unparam
    - unused
    - whitespace

  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - cyclop
          - dupl
          - errcheck
          - funlen
          - gosec
          - gocognit
          - gocyclo
          - lll
          - nestif
          - nakedret
      - linters:
          - lll
        source: "^\t*// "
      - path: "\\.go"
        linters:
          - funlen
      - linters:
          - errcheck
        source: "Fprint"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
