upstream: http://localhost:9095
insecure_listen_addr: 0.0.0.0:7777
internal_listen_addr: 0.0.0.0:7776
proxy_paths:
  - /api/v1/query
passthrough_paths:
  - /favicon.ico
proxy_read_timeout: 5s
proxy_write_timeout: 5s
proxymw_config:
  enable_jitter: true
  jitter_delay: 5s
  enable_observer: true
  backpressure_config:
    enable_backpressure: true
    backpressure_monitoring_url: http://localhost:9095
    backpressure_queries:
      - query: sum(rate(throughput[1m]))
        warning_threshold: 5000
        emergency_threshold: 8000
    congestion_window_min: 10
    congestion_window_max: 100
